name: Update README

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at 00:00 UTC 
  workflow_dispatch:

permissions:
  contents: write  
  
jobs:
  ping-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Ping GitHub Stats Graph
        run: |
          curl -s "https://github-readme-stats.vercel.app/api?username=abhi0395" > /dev/null
          curl -s "https://github-readme-activity-graph.vercel.app/graph?username=abhi0395" > /dev/null

